[tool.poetry]
name = "django-public-admin"
version = "0.0.1"
description = "A public read-only version of the Django Admin"
authors = ["Eduardo Cuducos <cuducos@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
django = "^2.0.0"

[tool.poetry.dev-dependencies]
Black = "^19.10b0"
pytest-django = "^3.8.0"
pytest-mock = "^2.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
